### PR TITLE
Update .travis.yml

### LINKED ISSUE #53: CI is broken
It's erroring out during `dpkg install` of some java-related thing: https://travis-ci.com/aio-libs/aiocassandra/jobs/150197735#L469

### PR DESCRIPTION
**Pull request by FedirAlifirenko**
trying to fix https://github.com/aio-libs/aiocassandra/issues/53

### CODE REVIEW

**Comment by asvetlov** [comment]
@hellysmile could you take a look?

**Review by webknjaz — CHANGES_REQUESTED** [review]
This doesn't look right at all

**Comment by FedirAlifirenko** [comment]
> This doesn't look right at all

@webknjaz Why do you think so? I see that cassandra package installs successfully https://travis-ci.com/aio-libs/aiocassandra/jobs/176539844#L688

**Comment by webknjaz** [comment]
Going away from declarative syntax is odd

**Comment by webknjaz** [comment]
Why not switch to `xenial` after all? It should have `dpkg` version fixed. We're migrating over to it in other repos across the org anyway...

**Review by webknjaz — APPROVED** [review]

**Pull request merged**
